# Generated by Django 6.0.1 on 2026-01-15 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id_lead', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('alt_mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_no', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('company_id', models.IntegerField(default=1)),
                ('status', models.CharField(blank=True, choices=[('sale_done', 'Sale Done'), ('interested_follow_up', 'Interested - Follow Up'), ('not_available', 'Not Available'), ('rnr', 'RNR'), ('not_interested', 'Not Interested'), ('out_of_country', 'Out of Country'), ('getting_better_deal', 'Getting Better Deal'), ('product_expensive', 'Product is Expensive'), ('not_eligible_emi', 'Not Eligible for EMI'), ('wrong_number', 'Wrong Number'), ('switched_off', 'Switched Off'), ('closed', 'Closed'), ('call_back', 'Call Back'), ('in_few_months', 'In Few Months'), ('contacted', 'Contacted'), ('lead', 'Lead')], default='lead', max_length=100, null=True)),
                ('status_description', models.TextField(blank=True, null=True)),
                ('converted', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('do_not_call', models.BooleanField(default=False)),
                ('followup_datetime', models.DateTimeField(blank=True, null=True)),
                ('followup_remarks', models.TextField(blank=True, null=True)),
                ('date_reviewed', models.DateField(blank=True, null=True)),
                ('course_id', models.CharField(blank=True, max_length=36, null=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('lead_source', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_source_description', models.TextField(blank=True, null=True)),
                ('refered_by', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_id', models.CharField(blank=True, max_length=36, null=True)),
                ('exp_revenue', models.CharField(blank=True, max_length=255, null=True)),
                ('exp_close_date', models.DateField(blank=True, null=True)),
                ('transfer_from', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_by', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('team_member', models.TextField(blank=True, null=True)),
                ('next_step', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created', to=settings.AUTH_USER_MODEL)),
                ('modified_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationHistory',
            fields=[
                ('id_comm_history', models.AutoField(primary_key=True, serialize=False)),
                ('communication_type', models.CharField(blank=True, choices=[('call', 'Call'), ('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=50, null=True)),
                ('template_details', models.TextField(blank=True, null=True)),
                ('text_msg', models.TextField(blank=True, null=True)),
                ('media_details', models.TextField(blank=True, null=True)),
                ('call_recording', models.TextField(blank=True, null=True)),
                ('sent_datetime', models.DateTimeField(blank=True, null=True)),
                ('receive_datetime', models.DateTimeField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(db_column='id_lead', on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='dashboard.lead')),
            ],
            options={
                'verbose_name_plural': 'Communication Histories',
                'db_table': 'communication_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackOfficeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bo_cat', models.CharField(blank=True, max_length=255, null=True)),
                ('bo_date', models.DateField(blank=True, null=True)),
                ('bo_status', models.CharField(blank=True, max_length=255, null=True)),
                ('bo_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('bo_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bo_updates', to='dashboard.lead')),
            ],
            options={
                'db_table': 'back_office_updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='dashboard.lead')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lead Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboard.lead')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lead_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('action', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dashboard.lead')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lead Histories',
                'db_table': 'lead_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
