# Generated by Django 5.2.11 on 2026-02-09 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_backofficeupdate_id_alter_company_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='assigned_user_id',
            new_name='assigned_user',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='modified_user_id',
            new_name='modified_user',
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='assignment_history',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company_id', 'status'], name='leads_company_25ca34_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_user', 'status'], name='leads_assigne_25dfae_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_by', 'created_at'], name='leads_created_5105f5_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['followup_datetime'], name='leads_followu_d976db_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_source'], name='leads_lead_so_f62041_idx'),
        ),
    ]
