# Generated by Django 6.0.1 on 2026-02-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='duplicate_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lead',
            name='duplicate_status',
            field=models.CharField(choices=[('new', 'New'), ('exact_duplicate', 'Exact Duplicate'), ('potential_duplicate', 'Potential Duplicate'), ('related', 'Related Lead')], default='new', max_length=20),
        ),
    ]
