# Generated by Django 6.0.2 on 2026-02-20 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_lead_duplicate_info_lead_duplicate_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='followup_priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='internal_reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='internal_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_internal_reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='team_followup_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InternalNotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('followup_reminder', 'Follow-up Reminder'), ('overdue_followup', 'Overdue Follow-up'), ('urgent_followup', 'Urgent Follow-up'), ('escalation', 'Escalation Notice'), ('daily_summary', 'Daily Team Summary'), ('weekly_summary', 'Weekly Team Summary'), ('team_performance', 'Team Performance Alert')], max_length=50)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Internal Email'), ('sms', 'Internal SMS')], max_length=10)),
                ('subject_template', models.CharField(blank=True, max_length=200, null=True)),
                ('body_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('company_id', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'internal_notification_templates',
                'ordering': ['template_type', 'name'],
                'indexes': [models.Index(fields=['template_type', 'channel'], name='internal_no_templat_1c8545_idx'), models.Index(fields=['company_id', 'is_active'], name='internal_no_company_83e554_idx')],
            },
        ),
        migrations.CreateModel(
            name='InternalFollowUpReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('followup', 'Follow-up Reminder'), ('task', 'Task Reminder'), ('meeting', 'Meeting Reminder'), ('deadline', 'Deadline Reminder'), ('escalation', 'Escalation Reminder')], default='followup', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('scheduled_datetime', models.DateTimeField()),
                ('followup_datetime', models.DateTimeField()),
                ('reminder_before_minutes', models.PositiveIntegerField(default=30)),
                ('notification_channels', models.CharField(choices=[('in_app', 'In-App Only'), ('email', 'Internal Email Only'), ('sms', 'Internal SMS Only'), ('email_sms', 'Email + SMS'), ('all', 'All Internal Channels')], default='in_app', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('team_notes', models.TextField(blank=True, null=True)),
                ('escalate_to_manager', models.BooleanField(default=False)),
                ('escalate_to_team_lead', models.BooleanField(default=False)),
                ('escalation_minutes', models.PositiveIntegerField(default=60)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_channel', models.CharField(blank=True, max_length=20, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('company_id', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_internal_reminders', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_reminders', to='dashboard.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'internal_follow_up_reminders',
                'ordering': ['scheduled_datetime'],
                'indexes': [models.Index(fields=['scheduled_datetime', 'status'], name='internal_fo_schedul_b8b9aa_idx'), models.Index(fields=['user', 'status'], name='internal_fo_user_id_cda4d1_idx'), models.Index(fields=['lead', 'status'], name='internal_fo_lead_id_7c53b9_idx'), models.Index(fields=['priority', 'scheduled_datetime'], name='internal_fo_priorit_7cabd6_idx'), models.Index(fields=['company_id', 'status'], name='internal_fo_company_8cec91_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeamNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('followup_reminder', 'My Follow-up Reminders'), ('overdue_followup', 'My Overdue Follow-ups'), ('team_reminder', 'Team Follow-up Alerts'), ('escalation', 'Escalation Notices'), ('daily_summary', 'Daily Team Summary'), ('weekly_summary', 'Weekly Team Summary'), ('performance_alert', 'Performance Alerts')], max_length=50)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('daily_summary_enabled', models.BooleanField(default=False)),
                ('weekly_summary_enabled', models.BooleanField(default=False)),
                ('team_alerts_enabled', models.BooleanField(default=True)),
                ('escalation_alerts_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_notification_preferences',
                'ordering': ['user', 'notification_type'],
                'indexes': [models.Index(fields=['user', 'notification_type'], name='team_notifi_user_id_1fe4fd_idx')],
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
