# Generated by Django 6.0.2 on 2026-03-26 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_lead_followup_priority_lead_internal_reminder_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='duplicate_group_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='duplicate_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='duplicate_resolution_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('ignored', 'Ignored'), ('merged', 'Merged')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='duplicate_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='duplicate_resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_duplicates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_assigned_agent_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_assigned_manager_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['duplicate_status', 'duplicate_resolution_status'], name='leads_duplica_47a9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['duplicate_group_id'], name='leads_duplica_4b2f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['last_assigned_agent', 'duplicate_status'], name='leads_last_as_8b36e4_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['last_assigned_manager', 'duplicate_status'], name='leads_last_as_9a76e5_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company_id', 'duplicate_status'], name='leads_company_21f1c2_idx'),
        ),
    ]
