# Generated by Django 6.0.2 on 2026-03-27 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_downloadfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='downloadfile',
            name='download_fi_is_acti_3e8396_idx',
        ),
        migrations.DeleteModel(
            name='DownloadFile',
        ),
        migrations.AddField(
            model_name='lead',
            name='original_assigned_user',
            field=models.ForeignKey(blank=True, help_text='Original user this lead was assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='primary_sales_credit',
            field=models.ForeignKey(blank=True, help_text='Original user who gets sales credit for converted leads', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='sales_credit_preserved',
            field=models.BooleanField(default=False, help_text='Whether sales credit has been preserved due to user deletion'),
        ),
    ]
