# Generated by Django 6.0.3 on 2026-04-02 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_downloadfile_download_fi_is_acti_3e8396_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('company_id', models.IntegerField(db_index=True, default=1)),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('preview_ready', 'Preview Ready'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='preview_ready', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('new_rows', models.PositiveIntegerField(default=0)),
                ('exact_duplicates', models.PositiveIntegerField(default=0)),
                ('potential_duplicates', models.PositiveIntegerField(default=0)),
                ('related_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('updated_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_id', 'status', 'created_at'], name='dashboard_l_company_fcd395_idx'), models.Index(fields=['company_id', 'idempotency_key'], name='dashboard_l_company_544d39_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('operation_type', models.CharField(choices=[('import_preview', 'Import Preview'), ('import_process', 'Import Process'), ('bulk_delete', 'Bulk Delete'), ('bulk_restore', 'Bulk Restore'), ('trash_purge', 'Trash Purge'), ('bulk_assign', 'Bulk Assign')], max_length=32)),
                ('company_id', models.IntegerField(db_index=True, default=1)),
                ('action_scope', models.CharField(default='current_page', max_length=20)),
                ('filter_snapshot', models.TextField(blank=True, null=True)),
                ('requested_count', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_id', 'operation_type', 'created_at'], name='dashboard_l_company_6fb001_idx')],
            },
        ),
    ]
