# Generated by Django 5.2.13 on 2026-04-11 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_leadimportsession_leadoperationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='backofficeupdate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='internalfollowupreminder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='internalnotificationtemplate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leadcomment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leadhistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leadimportsession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leadoperationlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teamnotificationpreference',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BulkOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('operation_type', models.CharField(choices=[('bulk_assign', 'Bulk Assign'), ('bulk_delete', 'Bulk Delete'), ('bulk_reassign_duplicates', 'Bulk Reassign Duplicates'), ('user_deletion_reassign', 'User Deletion Reassign'), ('bulk_import', 'Bulk Import'), ('bulk_export', 'Bulk Export')], max_length=50)),
                ('company_id', models.IntegerField(db_index=True, default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Estimated duration in seconds', null=True)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('processed_items', models.PositiveIntegerField(default=0)),
                ('success_items', models.PositiveIntegerField(default=0)),
                ('failed_items', models.PositiveIntegerField(default=0)),
                ('skipped_items', models.PositiveIntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0.0, help_text='Progress percentage (0-100)')),
                ('operation_config', models.JSONField(blank=True, default=dict, help_text='Operation configuration')),
                ('filter_snapshot', models.JSONField(blank=True, default=dict, help_text='Filter parameters snapshot')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, default=dict, help_text='Detailed error information')),
                ('items_per_second', models.FloatField(default=0.0, help_text='Processing rate')),
                ('peak_memory_usage', models.BigIntegerField(blank=True, help_text='Peak memory usage in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_operations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkOperationProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.CharField(db_index=True, max_length=64)),
                ('current_batch', models.PositiveIntegerField(default=0, help_text='Current batch number')),
                ('batch_size', models.PositiveIntegerField(default=0, help_text='Size of current batch')),
                ('total_batches', models.PositiveIntegerField(default=0, help_text='Total number of batches')),
                ('batch_success', models.PositiveIntegerField(default=0)),
                ('batch_failed', models.PositiveIntegerField(default=0)),
                ('batch_skipped', models.PositiveIntegerField(default=0)),
                ('cumulative_processed', models.PositiveIntegerField(default=0)),
                ('cumulative_success', models.PositiveIntegerField(default=0)),
                ('cumulative_failed', models.PositiveIntegerField(default=0)),
                ('cumulative_skipped', models.PositiveIntegerField(default=0)),
                ('batch_duration', models.FloatField(default=0.0, help_text='Duration of this batch in seconds')),
                ('cumulative_duration', models.FloatField(default=0.0, help_text='Total elapsed time in seconds')),
                ('batch_rate', models.FloatField(default=0.0, help_text='Items per second for this batch')),
                ('batch_details', models.JSONField(blank=True, default=dict, help_text='Detailed batch information')),
                ('error_samples', models.JSONField(blank=True, default=list, help_text='Sample errors from this batch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='dashboard.bulkoperation')),
            ],
            options={
                'db_table': 'bulk_operation_progress',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bulkoperation',
            index=models.Index(fields=['company_id', 'operation_type', 'status'], name='bulk_operat_company_4a90b2_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkoperation',
            index=models.Index(fields=['user', 'status'], name='bulk_operat_user_id_52a8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkoperation',
            index=models.Index(fields=['created_at'], name='bulk_operat_created_4eafe5_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkoperation',
            index=models.Index(fields=['operation_id'], name='bulk_operat_operati_a0ca04_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkoperationprogress',
            index=models.Index(fields=['operation', 'created_at'], name='bulk_operat_operati_b93af0_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkoperationprogress',
            index=models.Index(fields=['operation', 'current_batch'], name='bulk_operat_operati_86ea79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bulkoperationprogress',
            unique_together={('operation', 'update_id')},
        ),
    ]
