# Generated by Django 5.2.13 on 2026-04-15 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_add_error_details_to_import_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportProgressTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('company_id', models.IntegerField(db_index=True, default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('validating', 'Validating'), ('duplicate_checking', 'Checking Duplicates'), ('importing', 'Importing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('current_stage', models.CharField(default='starting', max_length=50)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('processed_records', models.PositiveIntegerField(default=0)),
                ('validated_records', models.PositiveIntegerField(default=0)),
                ('duplicate_checked_records', models.PositiveIntegerField(default=0)),
                ('imported_records', models.PositiveIntegerField(default=0)),
                ('failed_records', models.PositiveIntegerField(default=0)),
                ('skipped_records', models.PositiveIntegerField(default=0)),
                ('records_per_second', models.FloatField(default=0.0)),
                ('estimated_time_remaining', models.PositiveIntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['company_id', 'status', 'started_at'], name='dashboard_i_company_01911f_idx'), models.Index(fields=['session_id'], name='dashboard_i_session_cdca72_idx')],
            },
        ),
    ]
