# Generated by Django 6.0.2 on 2026-03-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preserved_converted_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of converted leads preserved after user deletion'),
        ),
        migrations.AddField(
            model_name='user',
            name='preserved_leads_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of leads preserved after user deletion'),
        ),
        migrations.AddField(
            model_name='user',
            name='preserved_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total revenue preserved from converted leads', max_digits=15),
        ),
    ]
